[package]
name = "tessellation-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tessellation = { path = "../.." }
wasm-bindgen = "0.2"
nalgebra = "0.33"
js-sys = "0.3"
getrandom = { version = "0.2", features = ["js"] }
